"""added saleEmail

Revision ID: 10413d6d85d4
Revises: 8be59d7f2996
Create Date: 2026-05-08 10:37:49.909515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10413d6d85d4'
down_revision = '8be59d7f2996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locationEmail', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('locationEmail')

    # ### end Alembic commands ###
