"""added book stars

Revision ID: 19e03a328e2a
Revises: 3a30fbca3ff9
Create Date: 2026-06-12 09:52:42.616848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e03a328e2a'
down_revision = '3a30fbca3ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('stars')

    # ### end Alembic commands ###
