"""added ord segs v23

Revision ID: 204aae2ecd1d
Revises: bec254ba9769
Create Date: 2026-06-05 15:55:22.534400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204aae2ecd1d'
down_revision = 'bec254ba9769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
